apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-config
data:
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_PASS: 200lab
  POSTGRES_DNS: "postgres://crawler:200lab@postgres-0.postgres:5432/crawler?sslmode=disable"
